name: Cat Image on Push

on: [push]

jobs:
    cat-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install requets
              run: pip install requests

            - run: python -u main.py

            - run: |
                  git config --local user.email "jhjjhjkhj@gmail.com"
                  git config --local user.name "TiboJhjj"
                  git add .
                  git commit -m "Add file"
                  git push
